// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"TaskList/driver"
	"TaskList/internal/task"
	"github.com/google/wire"
)

// Injectors from wire.go:

func BuildTaskSrv() task.Service {
	db := driver.InitGorm()
	repository := task.NewTaskRepo(db)
	service := task.NewTaskService(repository)
	return service
}

// wire.go:

var gormSet = wire.NewSet(driver.InitGorm)

var TaskServiceSet = wire.NewSet(task.NewTaskService, task.NewTaskRepo)
